# Generated by Django 5.1.3 on 2024-11-14 17:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "News", "verbose_name_plural": "News"},
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
