# Generated by Django 5.1.3 on 2024-11-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_news_options_alter_news_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
