# Generated by Django 5.1.3 on 2024-11-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_news_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_bot_token",
                    models.CharField(
                        help_text="Telegram bot uchun token", max_length=255
                    ),
                ),
                (
                    "telegram_channel_id",
                    models.CharField(
                        help_text="Telegram kanalining ID yoki username", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Sozlama",
                "verbose_name_plural": "Sozlamalar",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "Yangilik", "verbose_name_plural": "Yangiliklar"},
        ),
    ]
