# Generated by Django 5.1.3 on 2024-11-14 18:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_config_alter_news_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=ckeditor.fields.RichTextField(
                help_text="Yangilik kontentini shu yerda yozing"
            ),
        ),
    ]
