# Generated by Django 5.1.3 on 2024-11-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_news_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="telegram_channel_name",
            field=models.CharField(
                blank=True,
                help_text="Telegram kanal nomi majburiy emas",
                max_length=255,
                null=True,
            ),
        ),
    ]
